buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven {
            // 阿里云镜像，方便国内开发
            url = uri("https://maven.aliyun.com/repository/public/")
        }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '[6.0,6.2)', changing: true
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
        classpath 'org.parchmentmc:librarian:1.+'
        classpath 'gradle.plugin.com.github.johnrengelman:shadow:7.1.2'
    }
}


plugins {
    id 'eclipse'
    id 'idea'
    id 'java'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}


group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

configurations {
    libraries
    // This way, you only need one dependency declaration for both runtime and compile dependencies
    implementation.extendsFrom libraries
}
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

minecraft {

    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
            property 'geckolib.disable_examples', 'true'


        }
        client {}
        server {
            jvmArgs "-XX:+AllowEnhancedClassRedefinition"
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }

    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}
jarJar.enable()

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {

    flatDir {
        dir 'libs'
    }
    mavenLocal()
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "EDGtheXu's maven"
        url = "https://raw.githubusercontent.com/EDGtheXu/edg_thexu_maven/master/repository"
    }

// This is the repositories block in your build.gradle. NOT the one in publishing, or in buildscript. If it does not exist already, create it.
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }

    maven {
        name = "Curios"
        url = uri("https://maven.theillusivec4.top/")
    }
}
//configurations {
//    // 自定义一个 minecraftLibrary，方便引入需要 Shadow 的库
//    mcLib
//    minecraftLibrary {
//        extendsFrom mcLib
//    }
//}
//
//shadowJar {
//    configurations = [project.configurations.mcLib]
//
//    relocate('org.apache.commons.math3', 'org.confluence.terraentity.math3')
//
//    // 排除不需要的依赖项和资源
//    exclude 'META-INF/maven/**/*'
//    exclude 'META-INF/versions/**/*'
//    // 这个版权许可都已经手动添加进 licenses 里了
//    exclude 'META-INF/LICENSE'
//    exclude 'org/apache/commons/math3/**'
//    mergeServiceFiles()
//    minimize()
//}
//reobf {
//    shadowJar {}
//}

boolean dev = project.hasProperty('dev')
        ? project.property('dev').toBoolean()
        : true // 默认为true，设置dev=false时，会使用本地jar包

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // JEI
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-common-api:15.20.0.106")
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge-api:15.20.0.106")
    runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:15.20.0.106")

    if(dev){
        implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
    }else{
        implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
        jarJar("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}") {
            jarJar.ranged(it, "[${geckolib_version},)")
        }
    }
    implementation fg.deobf("curse.maven:curios-309927:6418456")


    implementation("com.eliotlash.mclib:mclib:20")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.6"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.3.6")) {
        jarJar.ranged(it, "[0.3.6,)")
    }

    // 数学库
    minecraftLibrary 'org.apache.commons:commons-math3:3.6.1'
    jarJar(implementation("org.apache.commons:commons-math3:3.6.1")){
        jarJar.ranged(it, "[3.6.1,)")
    }
//    compileOnly ("org.apache.commons:commons-math3:3.6.1")

    // 车万女仆
    compileOnly fg.deobf("curse.maven:touhou-little-maid-355044:6302618")
//    runtimeOnly fg.deobf("curse.maven:touhou-little-maid-355044:6302618")

    // jade
    compileOnly fg.deobf("curse.maven:jade-324717:6271651")
    runtimeOnly fg.deobf("curse.maven:jade-324717:6271651")



    compileOnly fg.deobf("curse.maven:dynamiclights-reforged-551736:6044481")
    runtimeOnly fg.deobf("curse.maven:dynamiclights-reforged-551736:6044481")

    compileOnly fg.deobf("curse.maven:sodium-options-api-1103431:6100812")
    runtimeOnly fg.deobf("curse.maven:sodium-options-api-1103431:6100812")

    compileOnly fg.deobf("curse.maven:embeddium-908741:5681725")
    runtimeOnly fg.deobf("curse.maven:embeddium-908741:5681725")


    // mc lib 要用lib:
    implementation fg.deobf("libs:cafelib:${cafelib_version}")
//    implementation fileTree(dir: 'libs', include: ['*.jar'])
    jarJar("com.github.edg_thexu:cafelib:${cafelib_version}") {
        jarJar.ranged(it, "[1.2.0,)")
    }

    // tacz, 多引入了math3，需要注释掉math3的mclib
//    implementation fg.deobf("curse.maven:timeless-and-classics-zero-1028108:7745481") {
//        exclude group: 'org.apache.commons', module: 'commons-math3'
//    }

    // 密码库
//    minecraftLibrary 'com.github.edg_thexu:vigsecurity:1.0.0.20'
//    implementation (files("libs/vigsecurity-1.0.0.20.jar"))
////    implementation 'com.github.edg_thexu:vigsecurity:1.0.0'
//    jarJar('com.github.edg_thexu:vigsecurity:1.0.0.20'){
//        jarJar.ranged(it, "[1.0.0,)")
//    }


//    implementation fg.deobf("curse.maven:kubejs-238086:5853326")
//    implementation fg.deobf("curse.maven:architectury-api-419699:5137938")
//    implementation fg.deobf("curse.maven:rhino-416294:6186971")

    //jarJar(implementation(fg.deobf("ignored:defaultresources-forge:1.19.2-0.3.0"))) {
    //    jarJar.ranged(it, "[0.3.0,)")
    //}
//    additionalRuntimeClasspath "org.apache.commons:commons-math3:3.6.1"


//    implementation fg.deobf("curse.maven:pehkui-319596:5393101")


    // 兼容azurelib读geo文件
//    implementation fg.deobf("curse.maven:azurelib-817423:6849107")

    //兼容azurelib armor读geo文件
    //implementation fg.deobf("curse.maven:azurelib-armor-912767:6004945")


}
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    finalizedBy 'reobfJar'
}

task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

tasks.withType(Copy).all { duplicatesStrategy 'exclude' }
